[package]
name = "gifgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
vt = { git = "https://github.com/asciinema/vt-rs.git" }
clap = { version = "3.2.15", features = ["derive"] }
gifski = "1"
imgref = "1"
rgb = "0.8"
resvg = "0.23"
usvg = { version = "0.23", features = ["text"] }
tiny-skia = "0.6"
fontdue = "0.7"
fontdb = "0.9"
log = "0.4"
env_logger = "0.9"
serde_json = "1.0.81"
serde = { version = "1.0.137", features = ["derive"] }
