[package]
name = "gifgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
# vt = { git = "https://github.com/asciinema/vt-rs.git" }
vt = { path = "../vt-rs" }
gifski = "*"
imgref = "*"
rgb = "*"
resvg ="*"
usvg = { version = "*", features = ["text"] }
tiny-skia = "*"
fontdue = "*"
fontdb = "*"
log = "0.4"
env_logger = "0.9"

# for asciicast
serde_json = "1.0.81"
serde = { version = "1.0.137", features = ["derive"] }
