name: "Build legacy Nix package on Ubuntu"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@19
      - name: Building package
        run: nix-build . -A defaultPackage.x86_64-linux
